name: linting, testing and building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: lint typesctipt
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ts
      - name: lint scss
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:scss
      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
      - name: build storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: storybook:build
      - name: test ui
        uses: borales/actions-yarn@v4
        with:
          cmd: test:ui:ci
